# Yolo

Below are two ways of loading Yolo.
I initially thought that in order to adjust the pretrained model I would need the `.yaml` but this ended up not working.
Both of these are almost equivalent, but after some testing, if the load that doesn't require the files works without a problem, I'll just use that and remove the extra files.

### Manual install

Let's skip this part. Remote load ftw

In [ ]:
'''
from yolo import Model

config_path = '../yolov5s-seg.yaml'
weights_path = '../yolov5s-seg.pt'

model = Model(config_path)

checkpoint = torch.load(weights_path, map_location='cpu')
model.load_state_dict(checkpoint['model'].state_dict(), strict=False)
'''



                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1   1182720  

<All keys matched successfully>

### Remote load

In [145]:
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5n6', pretrained=True)
#model = model.model.model
print(model)



Using cache found in /home/august/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2024-11-8 Python-3.12.2 torch-2.5.1+cu124 CPU

Fusing layers... 
YOLOv5n6 summary: 280 layers, 3239884 parameters, 0 gradients, 4.6 GFLOPs
Adding AutoShape... 


AutoShape(
  (model): DetectMultiBackend(
    (model): DetectionModel(
      (model): Sequential(
        (0): Conv(
          (conv): Conv2d(3, 16, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2))
          (act): SiLU(inplace=True)
        )
        (1): Conv(
          (conv): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
          (act): SiLU(inplace=True)
        )
        (2): C3(
          (cv1): Conv(
            (conv): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (cv3): Conv(
            (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (m): Sequential(
            (0): Bottleneck(
              (cv1): Conv(
                (conv): Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1))
  

In [84]:
pixel = 1280
image = torch.rand(1, 3, pixel, pixel)
model(image)


/home/august/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:865: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


tensor([[[3.87914e+00, 4.61340e+00, 1.53272e+01, 2.59218e+01, 4.25550e-01, 4.49479e-01],
         [1.16913e+01, 4.77067e+00, 1.39160e+01, 2.50988e+01, 4.42472e-01, 4.55111e-01],
         [1.94664e+01, 4.79392e+00, 1.41533e+01, 2.40440e+01, 4.37330e-01, 4.70713e-01],
         ...,
         [1.11402e+03, 1.23742e+03, 8.32489e+02, 6.82587e+02, 4.60790e-01, 5.35804e-01],
         [1.17759e+03, 1.23762e+03, 8.69414e+02, 7.13116e+02, 4.48060e-01, 5.40008e-01],
         [1.24056e+03, 1.24039e+03, 8.45446e+02, 6.70228e+02, 4.39121e-01, 5.44429e-01]]])

This is a simple way to look at the keys of the model weights
The weights themselves can be accessed by `model.state_dict()[key]`

These are groups of parameters, and they are numbered by layer.
We can use these to identify which parameters to freeze during fine tuning.


In [27]:

weights = model.state_dict()
for key in weights:
    print(key)

model.0.conv.weight
model.0.conv.bias
model.1.conv.weight
model.1.conv.bias
model.2.cv1.conv.weight
model.2.cv1.conv.bias
model.2.cv2.conv.weight
model.2.cv2.conv.bias
model.2.cv3.conv.weight
model.2.cv3.conv.bias
model.2.m.0.cv1.conv.weight
model.2.m.0.cv1.conv.bias
model.2.m.0.cv2.conv.weight
model.2.m.0.cv2.conv.bias
model.3.conv.weight
model.3.conv.bias
model.4.cv1.conv.weight
model.4.cv1.conv.bias
model.4.cv2.conv.weight
model.4.cv2.conv.bias
model.4.cv3.conv.weight
model.4.cv3.conv.bias
model.4.m.0.cv1.conv.weight
model.4.m.0.cv1.conv.bias
model.4.m.0.cv2.conv.weight
model.4.m.0.cv2.conv.bias
model.4.m.1.cv1.conv.weight
model.4.m.1.cv1.conv.bias
model.4.m.1.cv2.conv.weight
model.4.m.1.cv2.conv.bias
model.5.conv.weight
model.5.conv.bias
model.6.cv1.conv.weight
model.6.cv1.conv.bias
model.6.cv2.conv.weight
model.6.cv2.conv.bias
model.6.cv3.conv.weight
model.6.cv3.conv.bias
model.6.m.0.cv1.conv.weight
model.6.m.0.cv1.conv.bias
model.6.m.0.cv2.conv.weight
model.6.m.0.cv2.conv.bias
mo

# Adapting the model

Below I will adapt the model for threat detection.
The original pretrained model predicts 80 classes.
We are interested in binary classification, so the final layer will be a scalar.


In [146]:
import torch.nn as nn

sub_model = model.model.model
num_anchors = sub_model.model[-1].na  
sub_model.model[-1].nc = 1 # Number of outputs for binary classification
num_anchors = 1
sub_model.model[-1].no = num_anchors * (sub_model.model[-1].nc + 5)  

for i, conv in enumerate(sub_model.model[-1].m):
    in_channels = conv.in_channels
    out_channels = sub_model.model[-1].no * sub_model.model[-1].na  

    sub_model.model[-1].m[i] = nn.Conv2d(
        in_channels=in_channels,
        out_channels=out_channels,
        kernel_size=conv.kernel_size,
        stride=conv.stride,
        padding=conv.padding
    )

    torch.nn.init.normal_(sub_model.model[-1].m[i].weight, mean=0.0, std=0.01)
    torch.nn.init.constant_(sub_model.model[-1].m[i].bias, 0.0)

Here we test it out with a random image.
You will note that there the output is a 3D tensor.
Now the first dimension of course is just the batch, but why the $102000 \times 6$ matrix, when we wanted a scalar.
Well the answer is that Yolo breaks the image space into grids and makes a prediction about each grid location.
There are $102000$ predictions being made.
The $6$ is how it makes its prediction and scores

* x,y,w,h of the bounding box
* objectness: confidence that some object exists in the box
* confidence: The confidence that the object is in the class (threat)

There is an additional issue of this tensor taking a different form in training mode.
We want to keep it in training mode when we train so it doesn't mess up the internals of yolo.

In [147]:
model.eval()
out = model(image)
print(f'shape = {out.shape}')
print(f'output = {out}')

model.train()
out = model(image)
print(f'shape = {out[0].shape}')


/home/august/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:865: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
/home/august/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:865: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):


shape = torch.Size([2, 102000, 6])
output = tensor([[[2.90932e+00, 3.60545e+00, 1.40544e+01, 3.60025e+01, 5.02639e-01, 4.97406e-01],
         [1.10023e+01, 3.32069e+00, 1.44107e+01, 3.68102e+01, 4.86166e-01, 4.84209e-01],
         [1.89556e+01, 3.49945e+00, 1.51711e+01, 3.71174e+01, 4.65884e-01, 5.05324e-01],
         ...,
         [1.12293e+03, 1.24942e+03, 8.85134e+02, 9.37457e+02, 5.64633e-01, 5.08909e-01],
         [1.18651e+03, 1.24861e+03, 9.10876e+02, 9.21034e+02, 5.57338e-01, 5.08853e-01],
         [1.24867e+03, 1.24693e+03, 9.77977e+02, 9.18000e+02, 5.51443e-01, 5.16241e-01]],

        [[3.18700e+00, 3.48772e+00, 1.55447e+01, 3.67212e+01, 4.81376e-01, 5.09311e-01],
         [1.12526e+01, 3.25687e+00, 1.58933e+01, 3.67263e+01, 4.79241e-01, 4.97551e-01],
         [1.93645e+01, 3.40585e+00, 1.62613e+01, 3.70259e+01, 4.84051e-01, 5.03946e-01],
         ...,
         [1.12291e+03, 1.24875e+03, 8.94678e+02, 9.26008e+02, 5.61515e-01, 5.08145e-01],
         [1.18605e+03, 1.24805e+03, 

In [30]:
weights = model.state_dict()
for key in weights:
    print(key)

model.0.conv.weight
model.0.conv.bias
model.1.conv.weight
model.1.conv.bias
model.2.cv1.conv.weight
model.2.cv1.conv.bias
model.2.cv2.conv.weight
model.2.cv2.conv.bias
model.2.cv3.conv.weight
model.2.cv3.conv.bias
model.2.m.0.cv1.conv.weight
model.2.m.0.cv1.conv.bias
model.2.m.0.cv2.conv.weight
model.2.m.0.cv2.conv.bias
model.3.conv.weight
model.3.conv.bias
model.4.cv1.conv.weight
model.4.cv1.conv.bias
model.4.cv2.conv.weight
model.4.cv2.conv.bias
model.4.cv3.conv.weight
model.4.cv3.conv.bias
model.4.m.0.cv1.conv.weight
model.4.m.0.cv1.conv.bias
model.4.m.0.cv2.conv.weight
model.4.m.0.cv2.conv.bias
model.4.m.1.cv1.conv.weight
model.4.m.1.cv1.conv.bias
model.4.m.1.cv2.conv.weight
model.4.m.1.cv2.conv.bias
model.5.conv.weight
model.5.conv.bias
model.6.cv1.conv.weight
model.6.cv1.conv.bias
model.6.cv2.conv.weight
model.6.cv2.conv.bias
model.6.cv3.conv.weight
model.6.cv3.conv.bias
model.6.m.0.cv1.conv.weight
model.6.m.0.cv1.conv.bias
model.6.m.0.cv2.conv.weight
model.6.m.0.cv2.conv.bias
mo

In [11]:
model.eval()

DetectionModel(
  (model): Sequential(
    (0): Conv(
      (conv): Conv2d(3, 32, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2))
      (act): SiLU(inplace=True)
    )
    (1): Conv(
      (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (act): SiLU(inplace=True)
    )
    (2): C3(
      (cv1): Conv(
        (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
        (act): SiLU(inplace=True)
      )
      (cv2): Conv(
        (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
        (act): SiLU(inplace=True)
      )
      (cv3): Conv(
        (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
        (act): SiLU(inplace=True)
      )
      (m): Sequential(
        (0): Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  

In [ ]:
weights = model.state_dict()
for key in weights:
    print(key)

Now, as discussed this setup is not quite what we want.
Here how I plan to resolve this.
First, I will extract the prediction vectors for the objectness and class confidences.
These will be lineary projected onto a scalar value and the resulting logit will be converted to a probability through sigmoid.
The linear layer will of course be trainable.
This will effectively give us a single scalar value probability, which we can calculate cross entropy loss against our human labeled data.

I **could** demonstrate this in a few cells below, but I'm going to cut to the chase here.

Below I will define a class `YoloThreat` which encapsulates all of the functionality we need, and simply demonstrate that it works after.
Additionally, I'll make getting a freshly mutilated pretrained model easy, so we can declaritively pretrain these guys quickly.

The final important consideration is the downscaling.
1080p is $1920 \times 1080$ pixels.
For this we can use pytorch's interpolate function.
The thing is we don't want to do this during training because of added compute, but it is necessary functionality at inference.
We can simply preprocess our training, testing, and validation data to conform to the input size.
When deployed, the data is live so this needs to be built into the model.

In order to fix the training mode tensor shape issue, I adapted some code from the yolo source code.

I'll also make it so we can freeze layers at will for finetuning.

In [ ]:
import torch
import torch.nn.functional as F
import torch.nn as nn
from yolo import Segment

class YoloThreat(nn.Module):
    pixel = 1280
    base_model = 'yolov5n6'

    def __init__(self, yolo_model):
        super(YoloThreat, self).__init__()
        self.yolo = yolo_model
        self.yolo_pred_count = 102000
        self.fc = nn.Linear(self.yolo_pred_count * 2, 1)
        self.sigmoid = nn.Sigmoid()


    def forward(self, x):
        # Just incase the input is not batched, we add a batch dimension
        if len(x.shape) == 3:
            x = x.unsqueeze(0)
        # In evaluation mode, we rescale the input
        if not self.training:
            batch_size, _, _, _ = x.shape
            x = F.interpolate(x, size=(self.pixel, self.pixel), mode='bilinear', align_corners=False)

        yolo_out = self.yolo(x)
        if self.training:
            yolo_out = self.collect(yolo_out)
        else:
            yolo_out = yolo_out[-1]

        objectness = yolo_out[:, :, 4]
        class_probs = yolo_out[:, :, 5]
        yolo_out = torch.cat((objectness, class_probs), dim=-1)
        yolo_out = yolo_out.view(-1, self.yolo_pred_count * 2)

        logit = self.fc(yolo_out)
        return self.sigmoid(logit)
    
    # Adapted from Yolo source code. This reshapes the output tensor so we get the same shape in training and evaluation
    def collect(self, x):
        yolo = self.yolo.model[-1]  # Detect()
        z = []
        for i in range(yolo.nl):
            bs, _, ny, nx, _ = x[i].shape
            y = x[i].view(bs, yolo.na, yolo.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

            if yolo.dynamic or yolo.grid[i].shape[2:4] != x[i].shape[2:4]:
                        yolo.grid[i], yolo.anchor_grid[i] = yolo._make_grid(nx, ny, i)

            if isinstance(yolo, Segment):  # (boxes + masks)
                xy, wh, conf, mask = x[i].split((2, 2, yolo.nc + 1, yolo.no - yolo.nc - 5), 4)
                xy = (xy.sigmoid() * 2 + yolo.grid[i]) * yolo.stride[i]  # xy
                wh = (wh.sigmoid() * 2) ** 2 * yolo.anchor_grid[i]  # wh
                y = torch.cat((xy, wh, conf.sigmoid(), mask), 4)
            else:  # Detect (boxes only)
                xy, wh, conf = x[i].sigmoid().split((2, 2, yolo.nc + 1), 4)
                xy = (xy * 2 + yolo.grid[i]) * yolo.stride[i]  # xy
                wh = (wh * 2) ** 2 * yolo.anchor_grid[i]  # wh
                y = torch.cat((xy, wh, conf), 4)
            z.append(y.view(bs, yolo.na * nx * ny, yolo.no))

        return torch.cat(z, 1)
    
    '''
    Freeze all yolo layers below the specified layer number, and unfreeze the rest
    Enter 0 to unfreeze all layers
    '''
    def freeze_below(self, layer):
         if layer < 0 or layer > 34:
            raise ValueError('Layer number must be between 0 and 34')

         for name, param in self.yolo.named_parameters():
            name = name.split('.')
            if name[0] == 'yolo':
                if int(name[2]) < layer:
                    param.requires_grad = False
                    continue
            param.requires_grad = True

    @staticmethod
    def load_new_model():
        yolo_model = torch.hub.load('ultralytics/yolov5', YoloThreat.base_model, pretrained=True)
        yolo_model = yolo_model.model.model

        num_anchors = yolo_model.model[-1].na  
        yolo_model.model[-1].nc = 1 # Number of outputs for binary classification
        num_anchors = 1
        yolo_model.model[-1].no = num_anchors * (yolo_model.model[-1].nc + 5)  

        for i, conv in enumerate(yolo_model.model[-1].m):
            in_channels = conv.in_channels
            out_channels = yolo_model.model[-1].no * yolo_model.model[-1].na  

            yolo_model.model[-1].m[i] = nn.Conv2d(
                in_channels=in_channels,
                out_channels=out_channels,
                kernel_size=conv.kernel_size,
                stride=conv.stride,
                padding=conv.padding
            )

            torch.nn.init.normal_(yolo_model.model[-1].m[i].weight, mean=0.0, std=0.01)
            torch.nn.init.constant_(yolo_model.model[-1].m[i].bias, 0.0)

        return YoloThreat(yolo_model)

And now for a couple tests.
First when the pixels are the right size.

In [102]:
pixel = 1280
image = torch.rand(2, 3, pixel, pixel)

In [156]:
model = YoloThreat.load_new_model()
model.train()
out = model(image)
print(out)
model.eval()
out = model(image)
print(out)

x shape = torch.Size([2, 3, 1280, 1280])
tensor([[0.55576],
        [0.55440]], grad_fn=<SigmoidBackward0>)
x shape = torch.Size([2, 3, 1280, 1280])
tensor([[0.55576],
        [0.55440]], grad_fn=<SigmoidBackward0>)


And when they need to be downsized (only in eval)

In [157]:
image = torch.rand(2, 3, 1920, 1080)
model.eval()
out = model(image)
print(out)

x shape = torch.Size([2, 3, 1280, 1280])
tensor([[0.55731],
        [0.55573]], grad_fn=<SigmoidBackward0>)
